### ISSUE TITLE
Pelican theme preview

### ISSUE THREAD

**Issue by devty1023** [getpelican/pelican-themes#213]
There had to be a better way for me to preview all the pelican-themes in this repository instead of clicking on each candidates and hoping to see a live preview/screenshot. (is there??)

I created a small [website](http://pelican-preview.herokuapp.com/) that demos each theme. If the theme does not automatically generate an index.html, it is going to have a bad time... If the theme error on my compilation step for some reason, it is not included...

Source code for the webapp [here](https://github.com/devty1023/pelican-preview).

Hope the community finds this useful.

**Comment by purewhite2010** [comment]
I've written something similar, and used github pages to display a page of "previews" (probably should generate smaller preview images rather than CSS scaling) with links to each site. This could also be run in a cronjob with an automated push when changes are detected.
Some themes haven't generated properly, so your mileage may vary.

http://purewhite2010.github.io/pelican-theme-demos/

**Comment by ingwinlu** [comment]
https://github.com/ingwinlu/pelican-themes-previewer/

just throwing this out there since i will probably not get to it soon, uses a pelican plugin which parses the pelican-themes repository and generates them into articles.

can be used to also have an rss feed of themes, and all that other fancy stuff. if someone wants to pick up, feel free to hammer me with questions.

**Comment by kchr** [comment]
Please link to the theme preview solutions in this repository's README.rst or some other easily found place.

At least link to this thread!

**Comment by devty1023** [comment]
Better solution exists here!

https://github.com/m-allanson/pelican-themes

**Comment by ametaireau** [comment]
Nice! Don't hesitate to make a pull request on the pelican docs so that this site is showcased!
