### ISSUE TITLE
Google AMP Support

### ISSUE THREAD

**Issue by Telofy** [getpelican/pelican-themes#379]
Here’s a feature request: Are there plans for creating an [AMP-compatible](https://www.ampproject.org/) mobile version of one of the themes? Or would that be the wrong way of approaching it?

Thank you!

**Comment by justinmayer** [comment]
I'm not aware of any such plans. In many ways, it seems to me like a rather backwards approach. Mobile sites are only slow because some people choose to make slow sites. c.f., [An Internet Giant Tackles the Old Myth of "The Web is Too Slow"](http://arstechnica.com/information-technology/2015/11/googles-amp-an-internet-giant-tackles-the-old-myth-of-the-web-is-too-slow/).

That said, please feel free to create and submit a theme that supports this if it's something you are passionate about.  (^_^)

**Comment by Telofy** [comment]
Naw, I just want to get the SEO boost that Google promises to AMP sites. ;‑)

The more [technical talk here](https://www.ampproject.org/docs/get_started/technical_overview.html) is also honest about how it’s not faster than an actually well-made mobile site.

(It doesn’t seem like much work to make those tweaks, but I don’t think I’ll have time for it any time soon anyway.)

**Comment by derblub** [comment]
Anything new in this corner? I'm also looking forward to implement AMP to my current theme.

**Comment by justinmayer** [comment]
Folks are free to add (optional) AMP support to themes, but I think it's a big step backwards for the web, and I am totes not gonna spend any time on it.
