### ISSUE TITLE
pelicanthemes.com website throwing 500s

### ISSUE THREAD

**Issue by tidux** [getpelican/pelican-themes#731]
It looks like an Apache standard INTERNAL SERVER ERROR message.

**Comment by avaris** [comment]
It is working for me know. Also for the record, as far as I know, that site is a user project and is not handled by `pelican` maintainers. So, not much we can do either way :).

**Comment by Aluriak** [comment]
Same observation ; who are the authors ? Maybe can we tell them about that problem ?

**Comment by avaris** [comment]
Checked again. still working. I think the owner is here: https://github.com/m-allanson/pelican-themes

**Comment by Aluriak** [comment]
Mmmh. It is working now.

Looks like the problem was fixed, or that the server is down sometimes.

Thank you for the link, i will tell the author if i encounter the problem again.

**Comment by georgevreilly** [comment]
@justinmayer, http://pelicanthemes.com/ is down.

> Application error
>
> An error occurred in the application and your page could not be served. If you are the application owner, [check your logs for details](https://devcenter.heroku.com/articles/logging#view-logs). You can do this from the Heroku CLI with the command
> `heroku logs --tail`

<img width="733" alt="Screenshot 2022-12-23 at 12 13 23 AM" src="https://user-images.githubusercontent.com/34297/209298726-189c8098-6f79-417d-96d4-1afde728da38.png">

**Comment by justinmayer** [comment]
Yes, I’m aware, but it’s not a site that I control. If someone would like to help get it back up, please reach out to the person Deniz identified above and ask about what we can do to help get the site restored. Thanks!

**Comment by maphew** [comment]
In trying to work around this I had what seemed to be the bright idea of _"hey let's create a static site to preview a static site generator's themes"_ in Github Codespaces. At first I was excited because it seemed to work, but it turns out only `aboutwilson` is working. Perhaps someone else has some insight?

Here's my recipe.

```
pip install pelican[markdown]
gh repo clone getpelican/pelican-blog
gh repo clone getpelican/pelican-themes
cd pelican-themes
git submodule update --init --recursive
cd ..
````

Created `make-theme-outputs.sh` and fill with:

```
#!/bin/bash
for i in pelican-themes/b* ; do
  if [ -d "$i" ]; then
    theme=$(basename "$i")
    echo "### $theme ###"
    pelican \
      pelican-blog/content \
      --settings pelican-blog/pelicanconf.py \
      --theme-path pelican-themes/$theme \
      --output output/$theme \
      --ignore-cache \
      --delete-output-directory
  fi
done
```

Then make the script executable:  `chmod +x make-theme-outputs.sh` and (attempt to) generate all theme previews:

```
./make-theme-outputs.sh
```

If this or something like it could be fixed then it could be tied to github actions and a preview snapshot generated for each of them on merging their PR. Then there would be no reliance on 3rd party hosts.

**Comment by maphew** [comment]
See #740 for a publicly viewable and working implementation of https://github.com/getpelican/pelican-themes/issues/731#issuecomment-1365656511

**Comment by Rhomboid** [comment]
Please remove the reference to this url in your README, or point it to something that works. If the site has been dead for 6 months and you don't control the domain, you're just wasting everyone's time.

**Comment by justinmayer** [comment]
The original registrant of pelicanthemes.com and creator of the site that appeared on that domain was kind enough to reach out and ask if I wanted to take over the domain. So I paid for a year in order to start the transfer process, and as of 48 hours ago, I now have the ability to point pelicanthemes.com to wherever we decide it should resolve.

I should also mention that the person who created that site also offered to transfer to this organization the repository that contained the Flask-powered application that generated the site. I haven't had time to put much thought into whether that is the right approach, whether the solution that @maphew built might be better, or whether there are other approaches we should consider.

So for now I thought I would at least mention that we have a path to resolving this issue, as soon as we decide how exactly we want to do that.

**Comment by maphew** [comment]
that's cool! kudos to the domain owner for passing that on, and you Justin for picking up the bill. <3

I've no opinion on the Flask route as I've no experience with it. On general principle a static preview site for a static site generator is apropos. My solition is pretty basic though.

**Comment by datatalking** [comment]
@justinmayer 
Heroku is acting up, duplicate issue to gain visibility since its so forward facing

<img width="666" alt="Screen Shot 2023-05-08 at 1 51 14 PM" src="https://user-images.githubusercontent.com/11813209/236932889-088a8005-7861-4ffd-9267-7569459704d6.png">


> Mmmh. It is working now.
> 
> Looks like the problem was fixed, or that the server is down sometimes.
> 
> Thank you for the link, i will tell the author if i encounter the problem again.

**Comment by johann-petrak** [comment]
Is there any progress on making the site work again? I think having a site that does not work for a really long time might actually be worse than having no site at all.
For people who just want to use a tool like pelican, but NOT design their own themes, some easy way to pick a theme that fits their needs is absolutely essential, so I think having all the articles who talk about pelican link to http://www.pelicanthemes.com/ and then have that site be broken for a long time really hurts the pelican project.

**Comment by justinmayer** [comment]
@johann-petrak: As you can imagine, this is a known issue, the importance of which is already acknowledged. At the same time, project maintainers do their best with the limited time available for open-source development.

The most effective way to help move this forward is to [support Pelican development by becoming a sponsor](https://github.com/sponsors/justinmayer) 🌟

**Comment by jaideep2** [comment]
@justinmayer @avaris For your convenience [pelicanthemes.xyz](www.pelicanthemes.xyz) forwards to https://avaris.github.io/pelican-themes as a backup

**Comment by justinmayer** [comment]
@jaideep2: I appreciate the intention, but since we've already acquired the `pelicanthemes.com`  domain (as noted above), I'm not sure the domain name proliferation will be particularly helpful. There is already a comment to PR (748) in which I discuss how we might serve the generated assets directly from the `pelicanthemes.com`  domain.

**Comment by justinmayer** [comment]
https://pelicanthemes.com is now back up. Many thanks to @maphew and @avaris for their work on this! 🎊
